Add helm chart
FareHarbor/resourcebot pull request #6
Opened 2022-09-08 13:12 UTC by michalborkowski96

Add helm chart

2022-09-08 13:48 UTC, monester requested changes

2022-09-08 13:48 UTC, monester commented on cluster-bot-chart/templates/deployment.yaml
> +                  name: {{ .Values.slack_token_secret.name }}
it is a name of secret resource, it should not be a parameter. As well as key name.
Also I don't see secret resource definition.

2022-09-08 13:48 UTC, monester commented on cluster-bot-chart/templates/deployment.yaml
> +          args: ["resourcebot"]
this command already set in Dockerfile.

2022-09-08 15:12 UTC, michalborkowski96 commented on cluster-bot-chart/templates/deployment.yaml
> +          args: ["resourcebot"]
It didn't work for me locally, but now I see why. The command in Dockerfile has an extra space. Apparently it's not a problem for Docker, but breaks in kubernetes.

2022-09-09 11:33 UTC, monester commented on cluster-bot-chart/templates/deployment.yaml
> +                  name: {{ .Values.slack_token_secret.name }}
when you create a chart which is using another chart as base then it is worth to specify secret and key.
However it is not crucial so lgtm.

2022-09-09 11:33 UTC, monester approved these changes

2022-09-12 09:39 UTC, monester commented on cluster-bot-chart/templates/statefulset.yaml
> +kind: StatefulSet
why statefulset? why you can't use deployment?

2022-09-12 09:48 UTC, monester approved these changes

2022-09-12 11:39 UTC, merged